name: flutter_file_downloader
description: A new Flutter project.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_file_downloader
        pluginClass: FlutterFileDownloaderPlugin